version: "3.8"

services:
  landing:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: landing_psvivianapoveda
    restart: always
    ports:
      - "4321:80"
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3
    security_opt:
      - no-new-privileges:true
    networks:
      - landing_network
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M

networks:
  landing_network:
    driver: bridge 